#pragma once

#include "../VocaloidCoreGloble.h"

namespace vocaloid
{
    namespace vsm
    {

        enum VSMResult
        {
            NoError,
            OutOfMemory,
            InvalidArgument,
            FailedToCreateEditCommand,
            ObjectNotFound,
            ParentNotFound,
            InvalidPath,
            FailedToCopyFile,
            FileAlreadyExists,
            ObjectIsProtected,
            FailedToLoadVSM,
            CannotFindUid,
            FailedToGetHomeDir,
            FailedToCreateTempDir,
            FailedToCreateTempProject,
            FailedToMoveTempProject,
            FailedToCreateOutputDir,
            FailedToCreateSequenceUUID,
            FailedToCreateSequenceTempDir,
            InvalidSamplingRate,
            FailedToRemoveSameTimeEvent,
            MaxNumTrack,
            InvalidTrackType,
            MidiPartStartAbsolutePosTooSmall,
            MidiPartStartAbsolutePosTooLarge,
            MidiPartEndAbsolutePosTooLarge,
            MidiPartDurationTooShort,
            MidiPartDurationTooLong,
            InvalidDivideMidiPartPos,
            JoinMidiPartOfDifferentParent,
            EditCommandsStaging,
            ControllerRelativePosTooSmall,
            ControllerRelativePosTooLarge,
            ControllerAbsolutePosTooSmall,
            ControllerAbsolutePosTooLarge,
            CannotFindTargetTrack,
            CannotFindTopController,
            InvalidControllerType,
            NoteStartRelativePosTooSmall,
            NoteStartRelativePosTooLarge,
            NoteStartAbsolutePosTooSmall,
            NoteStartAbsolutePosTooLarge,
            NoteEndRelativePosTooLarge,
            NoteEndAbsolutePosTooLarge,
            NoteDurationTooShort,
            NoteDurationTooLong,
            InvalidNoteNumber,
            InvalidNoteVelocity,
            InvalidLyric,
            InvalidPhoneme,
            VibratoDurationTooShort,
            VibratoDurationTooLong,
            VibratoEventRelativePosTooSmall,
            VibratoEventRelativePosTooLarge,
            InvalidVibratoEventType,
            NoteEventsNotFound,
            MidiPartIsDisable,
            SequenceNotFound,
            SequenceTempDirPathNotFound,
            DatabaseManagerNotFound,
            VoiceBankNotFound,
            FailedToCreateVVoiceTable,
            FailedToGetDseModule,
            FailedToCreateDSE,
            FailedToStartDSE,
            FailedToOpenRenderedFile,
            FailedToCreateDseMidiEventsBuffer,
            FailedToCreateDseWaveBuffer,
            FailedToDseDoStepSynthesis,
            FailedToDseDoExportScore,
            FailedToCreateNRPN_Singer,
            PartialRendererNotCreated,
            DsePartialSynthNotStarted,
            FailedToResetDsePartialSynth,
            DuplicatedEffectID,
            DuplicatedEffectValueName,
            MidiEffectIsDisabled,
            FailedToInitVsqParserModule,
            FailedToCreateVsqParser,
            InvalidVsqxSchemaDirPath,
            FailedToParseVsqx,
            VsqObjTreeNotFound,
            InvalidVsqFormat,
            VsqRootNodeNotFound,
            VsqSequenceNotFound,
            VsqMasterTrackNotFound,
            VsqTempoNotFound,
            VsqTimeSigNotFound,
            VsqMixerNotFound,
            FailedToCreateJsonDoc,
            FailedToOpenJsonFile,
            FailedToParseJson,
            InvalidJsonDocRootType
        };

        std::string enumToString(VSMResult error);

    }
}
